apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      name: celery-beat
  template:
    metadata:
      labels:
        name: celery-beat
        tier: backend
    spec:
      containers:
        - name: celery-beat
          image: lokraj234/djangok8:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "celery -A app beat -l info"]
          envFrom:
            - configMapRef:
                name: django-config
          resources:
            requests:
              memory: 100Mi
              cpu: "100m"
            limits:
              memory: 100Mi
              cpu: "100m"
            
            # volume mounts if required