apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin   # Adjusted to match the label of pgadmin Pods
  type: NodePort
  ports:
    - port: 80
      targetPort: 80   # Port on the pod to forward traffic to
      nodePort: 30200
