apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/vol/shared"
