apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      name: django
  template:
    metadata:
      labels:
        name: django
        tier: backend
    spec:
      containers:
        - name: django
          image: lokraj234/djangok8:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "gunicorn --bind 0.0.0.0:8000 app.wsgi:application"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
          resources:
            limits:
              memory: 512Mi
              cpu: "250m"
            requests:
              memory: 512Mi
              cpu: "250m"
          # Volume mounts
          volumeMounts:
            - name: media-volume-mount
              mountPath: /vol/shared  # Directory inside the Django container

      # Volumes
      volumes:
        - name: media-volume-mount
          persistentVolumeClaim:
            claimName: django-pvc


    